[workspace]
members = [
    "fishmael-cache",
    "fishmael-cache-derive",
    "fishmael-gateway",
    "testbot",
]
resolver = "2"

[workspace.package]
name = "fishmael"
version = "0.1.0"
edition = "2021"
